#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_00.out08
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_00.out08
#PBS -q dev
#PBS -l select=1:ncpus=1
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N ukx_trk_00

# EXPORT list here
set -x
export envir=canned
export cmodel=ukmet
export NET=ens_tracker
export RUN=ukmet
export cyc=00
export job=tracker_ukx_00

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
#export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export ukmet_ver=v1.3
export PDY=20210823
module load prod_util/2.0.9
module load jasper/2.0.25
module load grib_util/1.2.3
module load libjpeg/9c
module load wgrib2/2.0.8
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
