#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_sref_03.out06
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_sref_03.out06
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=52:mpiprocs=26:mem=50GB
#PBS -l walltime=1:40:0
#PBS -A GFS-DEV
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB

set -x
export envir=canned
export cmodel=sref
export NET=sref
export RUN=sref
export cyc=03
export job=trkr_sref_03
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export sref_ver=${sref_ver:-v7.1}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
