#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nvgm_00.out31
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nvgm_00.out31
#PBS -q dev
#PBS -l select=1:ncpus=1
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N nvgm_trk_00

# EXPORT list here
set -x
export envir=canned
export cmodel=nvgm
export NET=nvgm
export RUN=navgem
export cyc=00
export job=tracker_nvgm_00
export PDY=20210824

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
##export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export gfs_ver=v16.2
export PDY=20210824
module load prod_util/2.0.8
module load jasper/2.0.25
module load grib_util/1.2.3
module load jasper/2.0.25
module load libjpeg/9c
module load wgrib2/2.0.8
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
