#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gfs_12.out21
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gfs_12.out21
#PBS -q dev
#PBS -l select=1:ncpus=1:mem=10GB
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N tracks_gfs_12

# EXPORT list here
set -x
export envir=canned
export cmodel=gfs
export NET=gfs
export RUN=gfs
export cyc=12
export job=tracks_gfs_12
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver

##-----------------------------------------------------------
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export gfs_ver=${gfs_ver:-v16.2}
export PDY=20210824
module load envvar/1.0
module load intel/19.1.3.304
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load cray-mpich/8.1.7
module load g2/3.4.5
module load jasper/2.0.25
module load libpng/1.6.37
module load zlib/1.2.11
module load w3emc/2.7.3
module load w3nco/2.4.1
module load bacio/2.4.1
module load libjpeg/9c
module load prod_envir/2.0.5
module load prod_util/2.0.9
module load grib_util/1.2.3
module load wgrib2/2.0.8
module load python/3.8.6
module load cray-pals/1.0.12

export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
