#BSUB -o /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_eens_00.o%J
#BSUB -e /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_eens_00.o%J
#BSUB -q dev
#BSUB -n 50
#BSUB -R "affinity[core]"
#BSUB -W 1:30
#BSUB -P FV3GFS-T2O
#BSUB -R "span[ptile=16]"
#BSUB -J eens_trk_00
# EXPORT list here
set -x
export envir=prod
export cmodel=eens
export NET=hourly
export RUN=ecme
export cyc=00
export job=tracker_eens_00

. /gpfs/dell2/emc/verification/noscrub/Guang.Ping.Lou/genesis_tracker.v3.4.9/jobs/JTRACKER.sms.$envir 20190825
