#BSUB -o /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_gefs_18.o%J
#BSUB -e /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_gefs_18.o%J
#BSUB -q dev
#BSUB -n 21
#BSUB -R "affinity[core]"
#BSUB -W 1:30
#BSUB -P FV3GFS-T2O
#BSUB -R "span[ptile=16]"
#BSUB -J gefs_trk
# EXPORT list here
set -x
export envir=prod
export cmodel=gefs
export NET=gens
export RUN=gefs
export cyc=18
export job=tracker_gefs_18

. /gpfs/dell2/emc/verification/noscrub/Guang.Ping.Lou/genesis_tracker.v3.4.9/jobs/JTRACKER.sms.$envir 20190825
