#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_12.out11
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_12.out11
#PBS -q dev
#PBS -l select=1:ncpus=1:mem=4GB
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N ukx_trk_12

# EXPORT list here
set -x
export envir=canned
export cmodel=ukmet
export NET=ens_tracker
export RUN=ukmet
export cyc=12
export job=tracker_ukx_12
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver

module list
module purge
module load envvar/$envvar_ver
module load intel/$intel_ver
module load prod_envir/$prod_envir_ver
module load PrgEnv-intel/$PrgEnv_intel_ver
module load craype/$craype_ver
module load cray-mpich/$cray_mpich_ver
module load cray-pals/$cray_pals_ver
module load jasper/$jasper_ver
module load libjpeg/$libjpeg_ver
module load prod_util/$prod_util_ver
module load grib_util/$grib_util_ver
module load wgrib2/$wgrib2_ver
module load python/$python_ver
##-----------------------------------------------------------
module list
##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export ukmet_ver=${ukmet_ver:-v1.3}
export PDY=20210823
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
