#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_fnmoc_12.out05
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_fnmoc_12.out05
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=42:mpiprocs=21
#PBS -A GFS-DEV
#PBS -l walltime=1:40:0
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB


set -x
export envir=canned
export cmodel=fens
export NET=gens
export RUN=fens
export cyc=12
export job=fens_trkr_12
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${TRACKER_VERSION}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
