#BSUB -o /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_ukx_00.o%J
#BSUB -e /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_ukx_00.o%J
#BSUB -q dev
#BSUB -n 1
#BSUB -R "affinity[core]"
#BSUB -W 0:40
#BSUB -P FV3GFS-T2O
#BSUB -R span[ptile=1]
#BSUB -J ukx_trk_00

# EXPORT list here
set -x
export envir=prod
export cmodel=ukmet
export NET=mrf
export RUN=ukmet
export cyc=00
export job=tracker_ukmet_00

. /gpfs/dell2/emc/verification/noscrub/Guang.Ping.Lou/genesis_tracker.v3.4.9/jobs/JTRACKER.sms.$envir 20190825
