#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_cens_00.out05
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_cens_00.out05
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=42:mpiprocs=21
#PBS -A GFS-DEV
#PBS -l walltime=1:40:0
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB


set -x
export envir=canned
export cmodel=cens
export NET=naefs
export RUN=cmce
export cyc=00
export job=trkr_cens_00
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
#export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export cens_ver=${cens_ver:-v6.1}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
