#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nam_18.out13
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nam_18.out13
#PBS -q dev
#PBS -l select=1:ncpus=1:mem=5GB
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N nam_trk_18

# EXPORT list here
set -x
export envir=canned
export cmodel=nam
export NET=nam
export RUN=nam
export cyc=18
export job=tracker_nam_18
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/versions/run.ver

module load envvar/1.0
module load intel/19.1.3.304
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load cray-mpich/8.1.7
module load g2/3.4.5
module load jasper/2.0.25
module load libpng/1.6.37
module load zlib/1.2.11
module load w3emc/2.7.3
module load w3nco/2.4.1
module load bacio/2.4.1
module load libjpeg/9c
module load prod_envir/2.0.5
module load prod_util/2.0.9
module load grib_util/1.2.3
module load wgrib2/2.0.8
module load python/3.8.6
module load cray-pals/1.0.12
##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${TRACKER_VERSION}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export nam_ver=${nam_ver:-v4.2}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
