#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nam_18.out13
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nam_18.out13
#PBS -q dev
#PBS -l select=1:ncpus=1:mem=5GB
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N nam_trk_18

# EXPORT list here
set -x
export envir=canned
export cmodel=nam
export NET=nam
export RUN=nam
export cyc=18
export job=tracker_nam_18
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export nam_ver=${nam_ver:-v4.2}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
