#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gefs_06.out07
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gefs_06.out07
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=64:mpiprocs=32
#PBS -l walltime=1:40:0
#PBS -A GFS-DEV
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB

set -x
##export envir=prod
export envir=canned
export cmodel=gefs
export NET=gens
export RUN=gefs
export cyc=06
export job=tracker_gefs_06
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${TRACKER_VERSION}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export gefs_ver=${gefs_ver:-v12.2}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
