#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nvgm_12.out19
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nvgm_12.out19
#PBS -q dev
#PBS -l select=1:ncpus=1
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N nvgm_trk_12

# EXPORT list here
set -x
export envir=canned
export cmodel=nvgm
export NET=nvgm
export RUN=navgem
export cyc=12
export job=tracker_nvgm_12

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
#export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export gfs_ver=v16.2
export PDY=20210826
module list
module load prod_util/2.0.9
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
