#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_00.out10
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_ukx_00.out10
#PBS -q dev
#PBS -l select=1:ncpus=1:mem=10GB
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N ukx_trk_00

# EXPORT list here
set -x
export envir=canned
export cmodel=ukmet
export NET=ens_tracker
export RUN=ukmet
export cyc=00
export job=tracker_ukx_00
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver


##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export ukmet_ver=${ukmet_ver:-v1.3}
export PDY=20210823
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
