#BSUB -o /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_sref_09.o%J
#BSUB -e /gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3/tracks_sref_09.o%J
#BSUB -q dev
#BSUB -n 26
#BSUB -R "affinity[core]"
#BSUB -W 1:30
#BSUB -P FV3GFS-T2O
#BSUB -R "span[ptile=16]"
#BSUB -J sref_trk
# EXPORT list here
set -x
export envir=prod
export cmodel=sref
export NET=sref
export RUN=sref
export cyc=09
export job=tracker_sref_09

. /gpfs/dell2/emc/verification/noscrub/Guang.Ping.Lou/genesis_tracker.v3.4.9/jobs/JTRACKER.sms.$envir 20190825
