#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_fnmoc_00.out04
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_fnmoc_00.out04
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=42:mpiprocs=21
#PBS -A GFS-DEV
#PBS -l walltime=1:40:0
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB


set -x
export envir=canned
export cmodel=fens
export NET=gens
export RUN=fens
export cyc=00
export job=fens_trkr_00

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
#export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export PDY=20210824
module load prod_util/2.0.8
module load jasper/2.0.25
module load grib_util/1.2.3
module load libjpeg/9c
module load wgrib2/2.0.8
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
