#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_sref_09.out05
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_sref_09.out05
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=52:mpiprocs=26
#PBS -l walltime=1:40:0
#PBS -A GFS-DEV
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB

set -x
export envir=canned
export cmodel=sref
export NET=sref
export RUN=sref
export cyc=09
export job=trkr_sref_09

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h1/ops/$envir/com
export COMROOTL=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export sref_ver=v7.1
export PDY=20210824
module load prod_util/2.0.8
module load grib_util/1.2.2
module load libjpeg/9c
module load wgrib2/2.0.8
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
