#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_cmc_12.out04
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_cmc_12.out04
#PBS -q dev
#PBS -l select=1:ncpus=1
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N cmc_trk_12

# EXPORT list here
set -x
export envir=canned
export cmodel=cmc
export NET=us007003
export RUN=cmc
export cyc=12
export job=tracker_cmc_00

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
#export COMROOT=/lfs/h1/ops/$envir/com
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export PDY=20210824
module load prod_util/2.0.9
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
