#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gfs_06.out09
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gfs_06.out09
#PBS -q dev
#PBS -l select=1:ncpus=1
#PBS -l walltime=0:40:0
#PBS -A GFS-DEV
#PBS -N tracks_gfs_06

# EXPORT list here
set -x
export envir=canned
export cmodel=gfs
export NET=gfs
export RUN=gfs
export cyc=06
export job=tracks_gfs_06
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/versions/run.ver

##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/ET_tracker
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${TRACKER_VERSION}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export gfs_ver=${gfs_ver:-v16.2}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/ET_tracker/jobs/JTRACKER
