#!/bin/sh
#PBS -o /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gefs_06.out09
#PBS -e /lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_gefs_06.out09
#PBS -q dev
#PBS -l place=vscatter,select=1:ncpus=64:mpiprocs=32:mem=100GB
#PBS -l walltime=1:40:0
#PBS -A GFS-DEV
######PBS -l select=1:ncpus=62:mpiprocs=31:mem=30GB

set -x
##export envir=prod
export envir=canned
export cmodel=gefs
export NET=gens
export RUN=gefs
export cyc=06
export job=tracker_gefs_06
source /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/versions/run.ver

module load envvar/1.0
module load intel/19.1.3.304
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load cray-mpich/8.1.7
module load g2/3.4.5
module load jasper/2.0.25
module load libpng/1.6.37
module load zlib/1.2.11
module load w3emc/2.7.3
module load w3nco/2.4.1
module load bacio/2.4.1
module load libjpeg/9c
module load prod_envir/2.0.5
module load prod_util/2.0.9
module load grib_util/1.2.3
module load wgrib2/2.0.8
module load python/3.8.6
module load cray-pals/1.0.12
##-----------------------------------------------------------
export NWROOT=/lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou
export HOMEgenesis_tracker=$NWROOT/genesis_tracker.v3.5.0
export DCOMROOT=/lfs/h1/ops/$envir/dcom
export COMROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
export DATAROOT=/lfs/h2/emc/ptmp/Guang.Ping.Lou
#export NWROOT=/lfs/h1/ops/$envir/packages
#export HOMEgenesis_tracker=$NWROOT/genesis_tracke.${genesis_tracker_ver}
#export COMROOT=/lfs/h1/ops/$envir/com
#export DATAROOT=/lfs/f1/ops/$envir/tmp
export gefs_ver=${gefs_ver:-v12.2}
export PDY=20210824
##-----------------------------------------------------------

. /lfs/h2/emc/vpppg/noscrub/Guang.Ping.Lou/genesis_tracker.v3.5.0/jobs/JTRACKER
