#!/bin/sh

########################################
# TROPICAL CYCLONE TRACKER SCRIPT
########################################

date
export PS4=' $SECONDS + ' 
set -x

# 
# obtain unique process id (pid) and make temp directories
#
export pid=${pid:-$$}
#export DATA=${DATA:-$DATAROOT/$jobid}
#export DATA=/ptmpp2/Guang.Ping.Lou/tmptrk
export DATA=/gpfs/dell2/ptmp/Guang.Ping.Lou/tmptrk
mkdir -p $DATA
cd $DATA
export cycle=${cycle:-t${cyc}z}

####################################
# Specify NET Name and model
#
# model - model grib field to repack
####################################
export NET=${NET:?}
export RUN=${RUN:?}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 
export CYC=$cyc

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $com
# SENDDBN  - Send files to OSO
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDOMB=${SENDOMB:-YES}

####################################
# Specify TRACKER version number
####################################
export TRACKER_VERSION=${TRACKER_VERSION:-${genesis_tracker_ver}}

################################
# Set up the HOME directory
################################
#export HOMEtracker=${HOMEtracker:-${NWROOT}/genesis_tracker.$TRACKER_VERSION}
export HOMEtracker=${HOMEDIR}/..
export SCRIPTStrkr=$HOMEtracker/scripts
export EXECtrkr=$HOMEtracker/exec
export FIXtrkr=$HOMEtracker/fix
export PARMtrkr=$HOMEtracker/parm
export USHtrkr=$HOMEtracker/ush

##############################
# Load modules
##############################
module load grib_util/1.0.6
module load prod_util/1.1.0

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
PDY=$1
if [ ${#PDY} -eq 0 ]
then
setpdy.sh
. PDY
fi
###############################################
# Define COMIN and COMOUT directory
###############################################

# COMIN for gfs, nam and arch
export machine=`hostname | cut -c1`
if [ $machine = v -o $machine = s -o $machine = g ]; then
export COMROOTp1=/gpfs/gp1/nco/ops/com
export COMROOT=/gpfs/gp2/nco/ops/com
export COMROOThps=/gpfs/hps/nco/ops/com
export DCOMROOT=/gpfs/gp1/nco/ops/dcom
else
export COMROOTp1=/gpfs/tp1/nco/ops/com
export COMROOT=/gpfs/tp2/nco/ops/com
export COMROOThps=/gpfs/hps/nco/ops/com
export DCOMROOT=/gpfs/tp1/nco/ops/dcom
fi
export namvitdir=${COMROOT}/nam/prod
export gfsvitdir=$(compath.py gfs/prod)
export archsyndir=${COMROOTp1}/arch/prod/syndat
# Input and output
#export COMGLTRK=${COMROOT}/gentracks/${envir}/gentracks
#export COMGLTRK=/meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7
export COMGLTRK=$HOMEtracker

# output
export tmscrdir=${COMROOTp1}/arch/${envir}

case $cmodel in
  gefs)  export COMIN=${COMROOT}/$NET/prod/${RUN}.$PDY/$CYC/pgrb2a
         export COMINtrack=${COMROOT}/$NET/prod/${RUN}.$PDY/$CYC/track
         export COMOUT=${COMROOT}/$NET/${envir}/${RUN}.$PDY/$CYC/track
         ;;
  fens)  export COMIN=${DCOMROOT}/us007003/${PDY}/wgrbbul/fnmocens_gb2
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY/$CYC/track
         ;;
  sref)  export COMIN=${COMROOT}/$NET/prod/${RUN}.$PDY/$CYC/pgrb
         export COMOUT=${COMROOT}/$NET/${envir}/${RUN}.$PDY/$CYC/track
         ;;
##  ecmwf) export COMIN=${DCOMROOT}/$NET/${PDY}/wgrbbul/${RUN}
  ecmwf) export COMIN=/dcomdev/us007003/ecmwf_test/
         export COMOUT=${COMROOTp1}/${RUN}/${envir}/${RUN}.${PDY}
         ;;
  eens)  export COMIN=${COMROOTp1}/$NET/prod/${RUN}.$PDY
         export ECEDIRIN=${COMROOT}/gens/prod/ecme.${PDY}
         export COMOUT=${COMROOTp1}/$NET/${envir}/${RUN}.$PDY
         ;;
  cens)  export COMIN=${COMROOThps}/naefs/para/${RUN}.$PDY/$CYC/pgrb2ap5
         export COMOUT=${COMROOT}/$NET/${envir}/${RUN}.$PDY/$CYC/track
         ;;
   cmc)  export COMIN=/${DCOMROOT}/us007003/$PDY/wgrbbul/cmc_gdps_25km
         export COMOUT=${COMROOTp1}/${RUN}/${envir}/${RUN}.${PDY}/track
         ;;
   gfs)  export COMIN=$(compath.py ${NET}/prod/${RUN}.$PDY)/${CYC}
##   gfs)  export COMIN=/gpfs/hps3/ptmp/emc.glopara/fv3fy18retro2/${RUN}.$PDY/${CYC}
##   gfs)  export COMIN=/gpfs/dell3/ptmp/emc.glopara/ROTDIRS/prfv3rt1/${RUN}.$PDY/${CYC}
##   gfs)  export COMIN=${COMROOThps}/${NET}/${envir}/${RUN}.$PDY
         export COMOUT=${COMROOThps}/${NET}/${envir}/${RUN}.$PDY
         ;;
   nvgm) export COMIN=${DCOMROOT}/us007003/$RUN
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}/track
         ;;
  ukmet) export COMIN=${COMROOT}/gens/${envir}/$RUN.${PDY}/${CYC}/pgrba
         export COMOUT=${COMROOThps}/$NET/${envir}/${RUN}.${PDY}/track
         ;;
  nam)   export COMIN=$(compath.py ${NET}/prod/${RUN}.$PDY)
         export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.$PDY
         ;;
   *)    export COMIN=${COMROOTp1}/$NET/prod/${RUN}.${PDY}
         export COMOUT=${COMROOTp1}/$NET/${envir}/${RUN}.${PDY}  
         ;;
esac

###########################################################
# COMOMB for daily track file 
# COMGLTRK for track archive file, yearly 
###########################################################
export COMOMB=${COMROOT}/omb/${envir}/tracker.${PDY}

mkdir -p $COMOUT $COMOMB $COMGLTRK

env

######################################
# Execute the script
######################################
export DO_TRACKER=${DO_TRACKER:-YES}

region="1 2"

export CYL=${CYL:-$cyc}
export init_flag=no
for reg in $region
do
  if [ $DO_TRACKER = YES ]
  then
     $HOMEtracker/scripts/exgenesis_tracker_poe.sh.ecf $PDY $CYL $cmodel $reg $init_flag
  fi
done

########################################################

cat $pgmout

date

if [ "$KEEPDATA" != YES ]; then
   cd $DATAROOT
#   rm -rf $DATA
fi
