#!/bin/sh

########################################
# TROPICAL CYCLONE TRACKER SCRIPT
########################################

date
export PS4=' $SECONDS + JTRACKER line $LINENO: ' 
set -x

# 
# obtain unique process id (pid) and make temp directories

export pid=${pid:-$$}
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir -p $DATA

cd $DATA
export cycle=${cycle:-t${cyc}z}

####################################
# Specify NET Name and model
#
# model - model grib field to repack
####################################
export NET=${NET:?}
export RUN=${RUN:?}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 
export CYC=$cyc

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $com
# SENDDBN  - Send files to OSO
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDOMB=${SENDOMB:-YES}

####################################
# Specify TRACKER version number
####################################
export genesis_tracker_ver=v3.4.15
export TRACKER_VERSION=${TRACKER_VERSION:-${genesis_tracker_ver}}

################################
# Set up the HOME directory
###########################
export HOMEtracker=$HOMEgenesis_tracker
export HOMEtracker=${HOMEtracker:-${NWROOT}/genesis_tracker.$TRACKER_VERSION}
export SCRIPTStrkr=$HOMEtracker/scripts
export EXECtrkr=$HOMEtracker/exec
export FIXtrkr=$HOMEtracker/fix
export PARMtrkr=$HOMEtracker/parm
export USHtrkr=$HOMEtracker/ush

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

###############################################
# Define COMIN and COMOUT directory
###############################################

# COMIN for gfs, nam and arch
export namvitdir=$(compath.py $envir/nam/v4.2)
export gfsvitdir=$(compath.py $envir/gfs/v16.2)
export archsyndir=${archsyndir:-$(compath.py $envir/gfs/v16.2/syndat)}
# Input and output
export COMGLTRK=${COMROOT}/gentracks/${envir}/gentracks

# output
export tmscrdir=${COMROOT}/gentracks/${envir}/arch

case $cmodel in
  gefs)  export COMIN=$(compath.py ${envir}/${cmodel}/${gefs_ver}/${RUN}.$PDY)/$CYC/atmos/pgrb2ap5
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
  fens)  export COMIN=${DCOMROOT}/${PDY}/wgrbbul/fnmocens_gb2
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
  sref)  export COMIN=$(compath.py ${envir}/${cmodel}/${sref_ver}/${RUN}.$PDY)/$CYC/pgrb
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
  ecmwf) export COMIN=${DCOMROOT}/${PDY}/wgrbbul/${RUN}
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}
         ;;
  eens)  export COMIN=$(compath.py ${envir}/${NET}/${eens_ver}/${RUN}.$PDY)
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
  cens)  export COMIN=$(compath.py ${envir}/${NET}/${cens_ver}/${RUN}.$PDY)/$CYC/pgrb2ap5
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
   cmc)  export COMIN=${DCOMROOT}/$PDY/wgrbbul/cmc_gdps_25km
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}
         ;;
   gfs)  export COMIN=$(compath.py ${envir}/${cmodel}/${gfs_ver}/${RUN}.$PDY)/$CYC/atmos
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
   nvgm) export COMIN=${DCOMROOT}/$RUN
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}
         ;;
  ukmet) export COMIN=$(compath.py ${envir}/${NET}/${ukmet_ver}/${RUN}.$PDY)
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}
         ;;
  nam)   export COMIN=$(compath.py ${envir}/${NET}/${nam_ver}/${RUN}.$PDY)
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.$PDY
         ;;
   *)   export COMIN=$(compath.py ${envir}/${NET}/${cmodel}_ver/${RUN}.$PDY)
         export COMOUT=${COMROOT}/gentracks/${envir}/${RUN}.${PDY}  
         ;;
esac

module list
###########################################################
# COMOMB for daily track file 
# COMGLTRK for track archive file, yearly 
###########################################################
export COMOMB=${COMROOT}/omb/${envir}/tracker.${PDY}
# For future:  export COMOMB=${COMROOT}/gentracks/${envir}/gentracks.${PDY}

mkdir -p $COMOUT $COMOMB $COMGLTRK $tmscrdir

env

######################################
# Execute the script
######################################
export DO_TRACKER=${DO_TRACKER:-YES}

region="1 2"

export CYL=${CYL:-$cyc}
export init_flag=no
for reg in $region
do
  if [ $DO_TRACKER = YES ]
  then
     $HOMEtracker/scripts/exgenesis_tracker_poe.sh.ecf $PDY $CYL $cmodel $reg $init_flag
  fi
done

########################################################

cat $pgmout

date
if [ "$KEEPDATA" != YES ]; then
   cd $DATAROOT
   rm -rf $DATA
fi
