#!/bin/sh

########################################
# TROPICAL CYCLONE TRACKER SCRIPT
########################################

date
export PS4=' $SECONDS + ' 
set -x

# 
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-/gpfs/dell2/ptmp/Guang.Ping.Lou/tmptrk}
export pid=${pid:-$$}
export DATA=${DATA:-$DATAROOT/$jobid}
mkdir -p $DATA
cd $DATA
export cycle=${cycle:-t${cyc}z}

####################################
# Specify NET Name and model
#
# model - model grib field to repack
####################################
export NET=${NET:?}
export RUN=${RUN:?}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 
export CYC=$cyc

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $com
# SENDDBN  - Send files to OSO
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDOMB=${SENDOMB:-YES}

####################################
# Specify TRACKER version number
####################################
TRACKER_VERSION=v3.4.9
export TRACKER_VERSION=${TRACKER_VERSION:-${genesis_tracker_ver}}

################################
# Set up the HOME directory
###########################
export HOMEtracker=/gpfs/dell2/emc/verification/noscrub/Guang.Ping.Lou/genesis_tracker.v3.4.9
export HOMEtracker=${HOMEtracker:-${NWROOT}/genesis_tracker.$TRACKER_VERSION}
#export HOMEtracker=/meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7
export SCRIPTStrkr=$HOMEtracker/scripts
export EXECtrkr=$HOMEtracker/exec
export FIXtrkr=$HOMEtracker/fix
export PARMtrkr=$HOMEtracker/parm
export USHtrkr=$HOMEtracker/ush

##############################
# Load modules
##############################
. $MODULESHOME/init/ksh
module purge
module load EnvVars/1.0.2
module load ips/18.0.1.163
module load impi/18.0.1
module load lsf/10.1
module load prod_util/1.1.1
module load grib_util/1.1.3
module load prod_envir/1.0.2
module load CFP/2.0.1

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
PDY=$1
if [ ${#PDY} -eq 0 ]
then
setpdy.sh
. PDY
fi
###############################################
# Define COMIN and COMOUT directory
###############################################

#comment out following two lines (COMROOTp3,COMROOT) before submit to NCO
##export COMROOTp3=/gpfs/dell1/nco/ops/com
#export COMROOTp3=/gpfs/dell2/ptmp/Guang.Ping.Lou/com/p1top3
#export COMROOThps=/gpfs/hps/nco/ops/com
#export DCOMROOT=/gpfs/tp1/nco/ops/dcom/
#export COMROOT=$COMROOTp3

# COMIN for gfs, nam and arch
export namvitdir=$(compath.py nam/prod)
export gfsvitdir=$(compath.py gfs/prod)
export archsyndir=${COMROOTp3}/gfs/prod/syndat
# Input and output
export COMGLTRK=${COMROOTp3}/gentracks/${envir}/gentracks

# output
export tmscrdir=${COMROOTp3}/arch/${envir}

case $cmodel in
  gefs)  export COMIN=$(compath.py ${NET}/prod/${RUN}.$PDY)/$CYC/pgrb2a
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
  fens)  export COMIN=${DCOMROOT}/us007003/${PDY}/wgrbbul/fnmocens_gb2
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
  sref)  export COMIN=$(compath.py $NET/prod/${RUN}.$PDY)/$CYC/pgrb
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
  ecmwf) export COMIN=${DCOMROOT}/$NET/${PDY}/wgrbbul/${RUN}
         export COMOUT=${COMROOTp3}/${RUN}/${envir}/${RUN}.${PDY}
         ;;
  eens) 
         export COMIN=${COMROOTp1}/$NET/prod/${RUN}.$PDY
         export ECEDIRIN=${COMROOThps}/ens_tracker/prod/ecme.${PDY}
         export COMOUT=${COMROOTp3}/$NET/${envir}/${RUN}.$PDY
         ;;
  cens)  export COMIN=${COMROOThps}/naefs/prod/${RUN}.$PDY/$CYC/pgrb2ap5
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
   cmc)  export COMIN=/${DCOMROOT}/us007003/$PDY/wgrbbul/cmc_gdps_25km
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.${PDY}/track
         ;;
   gfs)  export COMIN=$(compath.py ${NET}/prod/${RUN}.$PDY)/$CYC
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
   nvgm) export COMIN=${DCOMROOT}/us007003/$RUN
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.${PDY}/track
         ;;
  ukmet) export COMIN=${COMROOThps}/ens_tracker/prod/$RUN.${PDY}/${CYC}/pgrba
         export COMOUT=${COMROOTp3}/$NET/${envir}/${RUN}.${PDY}/track
         ;;
  nam)   export COMIN=$(compath.py ${NET}/prod/${RUN}.$PDY)
         export COMOUT=${COMROOTp3}/gentracks/${envir}/${RUN}.$PDY/track
         ;;
   *)    export COMIN=${COMROOTp1}/$NET/prod/${RUN}.${PDY}
         export COMOUT=${COMROOTp3}/$NET/${envir}/${RUN}.${PDY}  
         ;;
esac

###########################################################
# COMOMB for daily track file 
# COMGLTRK for track archive file, yearly 
###########################################################
export COMOMB=${COMROOT}/omb/${envir}/tracker.${PDY}

mkdir -p $COMOUT $COMOMB $COMGLTRK

env

######################################
# Execute the script
######################################
export DO_TRACKER=${DO_TRACKER:-YES}

region="1 2"

export CYL=${CYL:-$cyc}
export init_flag=no
for reg in $region
do
  if [ $DO_TRACKER = YES ]
  then
     $HOMEtracker/scripts/exgenesis_tracker_poe.sh.ecf $PDY $CYL $cmodel $reg $init_flag
  fi
done

########################################################

cat $pgmout

date
if [ "$KEEPDATA" != YES ]; then
   cd $DATAROOT
   rm -rf $DATA
fi
